name: Trigger Production in arc-jumpstart-app

on:
  push:
    branches:
      - canary

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Production Workflow 
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.REPO2_DISPATCH_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -d '{"event_type": "workflow-trigger", "client_payload": {"key": "value"}}' \
            https://api.github.com/repos/Azure/arc_jumpstart_web/dispatches
