name: Trigger Workflow in azure-arc-jumpstart-app

on:
  push:
    branches:
      - test-workflow  # Adjust the branch as needed

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.REPO2_DISPATCH_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'Azure',
              repo: 'arc_jumpstart_web',
              workflow_id: 'jumpstart_preview.yml',
              ref: 'test'
            })
